namespace me_workspace.Web.Data.Entities;

/// <summary>
/// Captures trend analysis results across multiple sources for a specific topic.
/// Generated by analyst agents during the council phase.
/// </summary>
public sealed class TrendAnalysis
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The project this analysis belongs to
    /// </summary>
    public Guid ProjectId { get; set; }

    /// <summary>
    /// Topic being analyzed (e.g., "vitamin cofactors", "synthetic vitamins")
    /// </summary>
    public string Topic { get; set; } = string.Empty;

    /// <summary>
    /// Summary of the trend findings
    /// </summary>
    public string TrendSummary { get; set; } = string.Empty;

    /// <summary>
    /// Number of sources that discuss this topic
    /// </summary>
    public int SourceCount { get; set; }

    /// <summary>
    /// Optional: Percentage of total sources that mention this topic
    /// </summary>
    public double? PrevalencePercent { get; set; }

    /// <summary>
    /// Optional: List of source IDs that contributed to this trend (JSON array)
    /// </summary>
    public string? SourceIds { get; set; }

    /// <summary>
    /// Optional: Key quotes or evidence (JSON format)
    /// </summary>
    public string? Evidence { get; set; }

    /// <summary>
    /// Optional: Recommendations based on this trend
    /// </summary>
    public string? Recommendations { get; set; }

    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

    // Navigation properties
    public Project Project { get; set; } = null!;
}
